[package]
name = "minitftpd"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["macros", "fs", "udp", "stream", "io-util"] }
futures = "0.3"
simon = "0.3"
